feat: add support for memorystore
porter-dev/porter-agent pull request #22
Opened 2022-09-28 12:44 UTC by meehawk

## Description

This PR introduces support for `logstore/memorystore`. An in-memory logstore used primarily for local testing and replication of the loki client

## Demo

Link to the REPL demonstrating the use: https://replit.com/join/kwdkscjyko-sohamparekh

2022-09-28 16:51 UTC, mnafees requested changes

2022-09-28 16:51 UTC, mnafees commented on pkg/logstore/memorystore/memorystore.go
> +	return path.Join("/var/tmp", store.name+".log")
This should use the `path/filepath` package's [`Join`](https://pkg.go.dev/path/filepath#Join) method like :
```go
filepath.Join("var", "tmp", store.name+".log")
```

2022-09-28 16:51 UTC, mnafees commented on pkg/logstore/memorystore/memorystore.go
> +	f, err := os.OpenFile(logFilePath, os.O_WRONLY|os.O_CREATE, 0666)
Is allowing for global read/write favorable? Or perhaps the filemode should be a more restrictive `0600`? @abelanger5 thoughts?

2022-09-28 19:21 UTC, meehawk commented on pkg/logstore/memorystore/memorystore.go
> +	f, err := os.OpenFile(logFilePath, os.O_WRONLY|os.O_CREATE, 0666)
@mnafees great flag, i ended up making it to 0600

2022-09-29 12:26 UTC, abelanger5 commented on pkg/logstore/memorystore/memorystore.go
> +	t, err := tail.TailFile(logFilePath, tail.Config{Follow: true})
Shouldn't we be initializing `t` in the `Stream` method? Otherwise each line in the file can only be read once. The `Stream` method shouldn't be a pure live tail, it should be able to stream historical logs as well, in the same manner as `tail -f ` or `kubectl logs -f`

2022-09-29 12:29 UTC, abelanger5 commented on pkg/logstore/logstore.go
> +	Stop () error
I'm not sure I understand having a separate `Stop()` method. We might want to pass a stopper channel to the Stream method instead

2022-09-29 16:06 UTC, abelanger5 commented on pkg/logstore/memorystore/memorystore.go
> +	go func(t *tail.Tail) {
We probably don't want to spawn a goroutine here - we still want `Stream` to be blocking so that it can return an error, and the caller can decide whether to spawn `Stream` as a goroutine.

2022-09-30 16:10 UTC, merged